services:
  db:
    image: bitnami/mysql:8.0.29-debian-10-r2
    restart: always
    volumes:
      - db_data:/bitnami/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=starwhale
      - MYSQL_USER=starwhale
      - MYSQL_PASSWORD=starwhale
      - MYSQL_DATABASE=starwhale
    network_mode: "host"

  oss:
    image: bitnami/minio:2022.6.20-debian-11-r0
    restart: always
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKETS=starwhale
      - MINIO_BROWSER=on
      - MINIO_CONSOLE_PORT_NUMBER=9001
    volumes:
      - oss_data:/data
    network_mode: "host"

  controller:
    image: docker-registry.starwhale.cn/starwhaleai/server:latest
    restart: always
    depends_on:
      - db
      - oss
    environment:
      - JAR=controller
      - SW_JWT_TOKEN_EXPIRE_MINUTES=144000
      - SW_UPLOAD_MAX_FILE_SIZE=20480MB
      - SW_SCHEDULER=docker
      # the ${GLOBAL_IP} should be the ip of the host machine that is accessible by all swcli clients including swcli in a user shell and swcli in pods
      - SW_METADATA_STORAGE_IP=${GLOBAL_IP}
      - SW_METADATA_STORAGE_PORT=3306
      - SW_METADATA_STORAGE_USER=starwhale
      - SW_METADATA_STORAGE_PASSWORD=starwhale
      - SW_STORAGE_BUCKET=starwhale
      - SW_STORAGE_ACCESSKEY=minioadmin
      - SW_STORAGE_SECRETKEY=minioadmin
      - SW_STORAGE_ENDPOINT=http://${GLOBAL_IP}:9000
      - SW_INSTANCE_URI=http://${GLOBAL_IP}:8082
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: "host"

volumes:
  db_data:
  oss_data:
  